
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 7.0.0
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - node_modules/selenium-standalone/bin/selenium-standalone install
  - babel-node --presets es2015,stage-0 ./src/server/server &
script:
  - npm test
