language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=7

# language: node_js
#
# node_js:
#   - "7"

env:
  global:
  - NODE_ENV=test

sudo: required

before_install:
  - "npm install selenium-standalone"
  - "./node_modules/selenium-standalone/bin/selenium-standalone install"
