language: node_js

node_js:
  - "7"

env:
  global:
  - NODE_ENV=test

sudo: required

before_install:
  - "npm install nightwatch babel-core babel-preset-stage-0 babel-preset-es2015"
  - "npm install -g selenium-standalone@6.2.0"
  - "selenium-standalone install"
