language: node_js

node_js:
  - "7"

env:
  global:
  - NODE_ENV=test

sudo: required

before_install:
  - "npm install nightwatch selenium-standalone@6.2.0 babel-core babel-preset-stage-0 babel-preset-es2015"
